apiVersion: v1
kind: Secret
metadata:
  name: graph-secret
type: Opaque
stringData:
  ethereum: "mumbai:rpcurl"
  postgres_host: <Postgres host>
  postgres_user: <Postgres user name>
  postgres_db: <Postgres Database name>
  postgres_pass: <Postgres pass>
